### PR TITLE
Added Typescript type definitions, and exported the lexer tokens.

### PR DESCRIPTION
**Pull request by dalyIsaac**
- Also incremented version number to 0.8.2
- Added .gitignore

### CODE REVIEW

**Comment by alwinb** [comment]
Thanks for taking an interest! I'm merging into the develop branch, as I wish to make some naming changes and reserve the master branch for releases from now on.

**Comment by alwinb** [comment]
I have made some changes, in https://github.com/alwinb/tiny-html-lexer/commit/b1328671514c4ef4ac94a180125e118d41dee5c7 I have modeled the TokenType as a union of string values and changed the definition to use the Iterator protocols. Does this work for you?

**Comment by dalyIsaac** [comment]
Yes that does, thanks!

**Comment by alwinb** [comment]
I have published version 0.8.3 on npm with the added typescript annotations.

**Comment by dalyIsaac** [comment]
Thanks! 😊

**Pull request merged**
